##### Dreamcacher配置 #####
data:
  input_data_path: /data/test_generated.jsonl
  output_data_path: /data/test_autolabeled.jsonl
  output_rank_data_path: null

scorer:
  similarity_scorer:
    embedding_model_path: /models/bge-large-zh-v1.5
    embedding_tokenizer_path: /models/bge-large-zh-v1.5
  
  unigram_scorer:
    unigram_top_k: 5

  probe_scorer:
    model_type: ziya
    hidden_size: 5120
    probe_model_path: /probe.pt
    probe_state_key: hidden_states
    probe_token: last
    probe_layer: n
    model_path: /model_path
    tokenizer_path: /model_path

ranker:
  null
